# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 23:30
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_hasonboarded'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=profiles.models.get_file_path)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('origFileName', models.CharField(blank=True, default=b'', max_length=260, verbose_name=b'name')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(default=profiles.models.metadata_default)),
                ('contentType', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
