# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='origFileName',
            field=models.CharField(blank=True, default=b'', max_length=260),
        ),
    ]
