# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20161122_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('username',)]),
        ),
    ]
