# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 09:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20161209_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianstudentrelation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GuardianStudentRelation_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
