# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20161212_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='avatar_url',
            field=models.URLField(blank=True, default=b'https://s3-ap-southeast-1.amazonaws.com/fcanectar/customMedia/defaultUserIcon.png', verbose_name=b'avatar_url'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default=b'https://s3-ap-southeast-1.amazonaws.com/fcanectar/customMedia/defaultUserIcon.png', verbose_name=b'avatar_url'),
        ),
    ]
