# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20161222_0345'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userschoolrelation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='userschoolrelation',
            name='school',
        ),
        migrations.RemoveField(
            model_name='userschoolrelation',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.School'),
        ),
        migrations.AlterField(
            model_name='school',
            name='avatar_url',
            field=models.URLField(blank=True, default=b'https://s3-ap-southeast-1.amazonaws.com/fcanectar/customMedia/schoolIcon.png', verbose_name=b'avatar_url'),
        ),
        migrations.DeleteModel(
            name='UserSchoolRelation',
        ),
    ]
