# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20161223_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, null=True, verbose_name=b'username'),
        ),
    ]
