# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20170117_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripeCustomerId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
