# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 09:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20170120_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='addressGoogleRef',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=profiles.models.metadata_default),
        ),
        migrations.AddField(
            model_name='user',
            name='heardFrom',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='needComputer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
