# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20170121_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='heardFromOption',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
