# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20170201_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='signBy',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
