# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20170203_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(b'G', b'guardian'), (b'S', b'student'), (b'I', b'instructor'), (b'O', b'operations'), (b'C', b'Chief Whatevers')], default=b'G', max_length=1),
        ),
    ]
