# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20170203_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReferral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='userreferral',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userreferral',
            unique_together=set([('user', 'email')]),
        ),
    ]
