# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_auto_20170211_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='stripeAcct',
            field=models.CharField(default=b'hkd', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='stripeAcct',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
