# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-25 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20170225_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='event_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='stripeAcct',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ledger',
            unique_together=set([('stripeAcct', 'event_id')]),
        ),
    ]
