# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 02:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20170225_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clientDump',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=profiles.models.metadata_default),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='stripeAcct',
            field=models.CharField(choices=[(b'twd', b'twd'), (b'sgd', b'sgd'), (b'hkd', b'hkd')], max_length=30, null=True),
        ),
    ]
