# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20170310_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditedUser', to=settings.AUTH_USER_MODEL)),
                ('referToUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referToUser', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='couponcourserelation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='couponcourserelation',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='couponcourserelation',
            name='course',
        ),
        migrations.RemoveField(
            model_name='couponuserrelation',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='couponuserrelation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='CouponCourseRelation',
        ),
        migrations.DeleteModel(
            name='CouponUserRelation',
        ),
        migrations.AlterUniqueTogether(
            name='referralcredit',
            unique_together=set([('referToUser', 'creditedUser')]),
        ),
    ]
