# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_referralcredit_isused'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralcredit',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
