# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 09:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_referralcredit_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='addressGoogleRef',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=profiles.models.metadata_default),
        ),
        migrations.AddField(
            model_name='school',
            name='enFormattedAddress',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='school',
            name='enName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
