# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_auto_20170327_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='enFormattedAddress',
        ),
    ]
