# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_remove_school_enformattedaddress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='school',
            unique_together=set([]),
        ),
    ]
