language_choices = (
  ('PYTHON', 'Python'),
  ('MINECRAFT', 'Minecraft'),
  ('3DPRINTING', '3DPrinting'),
  ('APPINVENTOR', 'AppInventor'),
  ('SCRATCH', 'Scratch'),
  ('JAVA', 'Java'),
  ('JS', 'JavaScript'),
  ('UNITY', 'Unity'),
  ('MBOT', 'mBot'),
  ('SWIFT', 'Swift'),
  ('HOPSCOTCH', 'Hopscotch'),
  ('ROBOTICS', 'Robotics'),
  ('SCRATCHX', 'ScratchX'),
  ('OTHER', 'Other'),
)