# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(blank=True, default=0)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('point', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('point', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('course_icon_url', models.URLField(blank=True, default=b'http://placehold.it/350x350')),
                ('eventbrite_tag', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True, default=b'http://placehold.it/350x350', verbose_name=b'avatar_url')),
                ('threshold', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserCourseRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[(b'S', b'student'), (b'I', b'instructor')], default=b'S', max_length=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usercourserelationship',
            unique_together=set([('user', 'course')]),
        ),
    ]
