# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 15:39
from __future__ import unicode_literals

import course.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20161122_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='point',
        ),
        migrations.AddField(
            model_name='challenge',
            name='ruleDefinition',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=course.models.awardDefinition_default),
        ),
        migrations.AddField(
            model_name='challengerecord',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Challenge'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='lesson',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set([('name', 'course')]),
        ),
    ]
