# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20161213_0641'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('course_code',)]),
        ),
    ]
