# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20161216_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='avatar_url',
            field=models.URLField(blank=True, default='https://s3-ap-southeast-1.amazonaws.com/fcanectar/customMedia/trophIcon.png', verbose_name='avatar_url'),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='language',
            field=models.CharField(choices=[('', 'None'), ('PYTHON', 'Python'), ('MINECRAFT', 'Minecraft'), ('3DPRINTING', '3DPrinting'), ('APPINVENTOR', 'AppInventor'), ('SCRATCH', 'Scratch'), ('JAVA', 'Java'), ('JS', 'JavaScript'), ('UNITY', 'Unity')], default='', max_length=20),
        ),
    ]
