# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 01:09
from __future__ import unicode_literals

import course.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20161222_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='awardDefinition',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='ruleDefinition',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=course.models.ruleDefinition_default),
        ),
    ]
