# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0008_auto_20170101_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=32)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='challengeprogress',
            unique_together=set([('user', 'challenge', 'signature')]),
        ),
    ]
