# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20170103_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophy',
            name='language',
            field=models.CharField(choices=[('', 'None'), ('PYTHON', 'Python'), ('MINECRAFT', 'Minecraft'), ('3DPRINTING', '3DPrinting'), ('APPINVENTOR', 'AppInventor'), ('SCRATCH', 'Scratch'), ('JAVA', 'Java'), ('JS', 'JavaScript'), ('UNITY', 'Unity'), ('MBOT', 'mBot'), ('SWIFT', 'Swift'), ('HOPSCOTCH', 'Hopscotch'), ('ROBOTICS', 'Robotics')], default='', max_length=20),
        ),
    ]
