# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20170113_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cnType',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
