# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 04:27
from __future__ import unicode_literals

import course.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20170207_0641'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClassDateRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignore', models.BooleanField(default=False)),
                ('startDateTime', models.DateTimeField()),
                ('endDateTime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='prices',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=course.models.makeEmptyList),
        ),
        migrations.AddField(
            model_name='courseclassdaterelationship',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
