# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_auto_20170209_0427'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseclassdaterelationship',
            unique_together=set([('course', 'startDateTime')]),
        ),
    ]
