# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_auto_20170209_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseclassdaterelationship',
            options={'ordering': ['-startDateTime']},
        ),
    ]
