# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0025_course_class_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='address',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_icon_url',
            field=models.URLField(blank=True, default='https://s3-ap-southeast-1.amazonaws.com/fcanectar/assets/firstcode_logo.png'),
        ),
    ]
