# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=None, max_length=4, null=True)),
                ('eventType', models.CharField(default=None, max_length=20, null=True)),
                ('batch', models.CharField(default=None, max_length=50, null=True)),
                ('period', models.CharField(default=None, max_length=50, null=True)),
                ('cohort', models.CharField(default=None, max_length=50, null=True)),
                ('course', models.CharField(default=None, max_length=100, null=True)),
                ('firstName', models.CharField(default=None, max_length=100, null=True)),
                ('lastName', models.CharField(default=None, max_length=100, null=True)),
                ('birthDate', models.DateField(default=None, null=True)),
                ('age', models.IntegerField(default=None, null=True)),
                ('gender', models.CharField(default=None, max_length=10, null=True)),
                ('school', models.CharField(default=None, max_length=100, null=True)),
                ('grade', models.CharField(default=None, max_length=10, null=True)),
                ('parentFirstName', models.CharField(default=None, max_length=100, null=True)),
                ('parentLastName', models.CharField(default=None, max_length=100, null=True)),
                ('parentEmail', models.CharField(default=None, max_length=200, null=True)),
                ('parentMobile', models.CharField(default=None, max_length=20, null=True)),
                ('homeAddress', models.CharField(default=None, max_length=500, null=True)),
                ('paid', models.CharField(default=None, max_length=20, null=True)),
                ('promoCode', models.CharField(default=None, max_length=50, null=True)),
                ('enrollmentDate', models.DateField(default=None, null=True)),
                ('howHeard', models.CharField(default=None, max_length=50, null=True)),
                ('comments', models.CharField(default=None, max_length=500, null=True)),
                ('eventbriteEventID', models.CharField(default=None, max_length=20, null=True)),
                ('eventbriteOrderID', models.CharField(default=None, max_length=20, null=True)),
                ('eventBriteOrderDate', models.CharField(default=None, max_length=20, null=True)),
                ('classLocation', models.CharField(default=None, max_length=10, null=True)),
            ],
        ),
    ]
