# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20161223_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='classLocation',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='eventBriteOrderDate',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='eventType',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='eventbriteEventID',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='eventbriteOrderID',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='grade',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketing',
            name='paid',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
