# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20161223_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='parentMobile',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
