# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_auto_20161223_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='enrollmentDate',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
