# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_marketing_guessschool'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='autoGuessSchool',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
