# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_eventbritedump'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(default=None, max_length=200, null=True)),
                ('startDate', models.DateTimeField()),
            ],
        ),
    ]
