# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadApp', '0004_auto_20161202_1900'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projecticonfile',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='projecticonfile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projecticonfile',
            name='userFile',
        ),
        migrations.AlterUniqueTogether(
            name='projectpackagefile',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='projectpackagefile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectpackagefile',
            name='userFile',
        ),
        migrations.AlterUniqueTogether(
            name='projectscreenshot',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='projectscreenshot',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectscreenshot',
            name='userFile',
        ),
        migrations.AddField(
            model_name='projectsourcefile',
            name='purpose',
            field=models.CharField(choices=[('screenshot', 'screenshot'), ('icon', 'icon'), ('package', 'package'), ('source', 'source')], default='G', max_length=1),
        ),
        migrations.DeleteModel(
            name='ProjectIconFile',
        ),
        migrations.DeleteModel(
            name='ProjectPackageFile',
        ),
        migrations.DeleteModel(
            name='ProjectScreenshot',
        ),
    ]
