# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadApp', '0005_auto_20161205_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsourcefile',
            name='purpose',
            field=models.CharField(choices=[('screenshot', 'screenshot'), ('icon', 'icon'), ('package', 'package'), ('source', 'source')], default='icon', max_length=15),
        ),
    ]
