# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadApp', '0006_auto_20161205_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='externalURL',
            field=models.URLField(blank=True, default=''),
        ),
    ]
