# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0005_auto_20161213_0641'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrophyRecordAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(0, 'Love'), (1, 'Like'), (2, 'Wow')], default=0)),
                ('trophyRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.TrophyRecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='trophyrecordaction',
            unique_together=set([('user', 'trophyRecord', 'action')]),
        ),
    ]
